### ISSUE TITLE
Can't run vagrant up

### ISSUE THREAD

**Issue by jlt20** [LangProc/langproc-2021-lab#10]
![image](https://user-images.githubusercontent.com/72909581/150649132-fbb56e1e-18b7-4579-b933-808ac86fee23.png)

Hi, can I have some help with this? Thanks!

**Comment by ymherklotz** [comment]
Hi, could you send some more information:

1. What operating system you are using (looks like Windows 10 maybe).
2. Did you install Virtual Box and Vagrant?
3. Did you try opening a new `cmd.exe` window and get the same result?

**Comment by jlt20** [comment]
1. Windows 11
2. Yes, i’ve installed it.
3. Yes, i’ve restarted my computer too.

**Comment by ymherklotz** [comment]
Then I really don't understand the error, because you are clearly already
running `cmd.exe`..  I found this thread which seems to be a similar error:

    https://forum.arduino.cc/t/exec-cmd-executable-file-not-found-in-path/410305/9

Two things you can try:

- Try running the CMD shell in administrator mode (seemed to solve it in the
thread above).
- For now you can use Windows Subsystem for Linux (WSL), which should work fine
for the lab and should give you nearly the same environment.
