### ISSUE TITLE
Error when encountering input files with words detected + leading whitespaces in stdout

### ISSUE THREAD

**Issue by ozeidan9** [LangProc/langproc-2021-lab#12]
1) I am experiencing the segmentation fault error shown below whenever my lexer detects a word from an input text file, which leads to a blank stdout file in all cases when a word is detected. What does 'Segmentation fault: 11' mean here?

![Screenshot 2022-01-22 at 11 38 43 pm](https://user-images.githubusercontent.com/94687744/150659146-a153681a-ba59-4743-b710-81b79d46ecd3.png)

2) As well as this, in some cases when the sum of the numbers in the input file is printed to stdout, the right output is produced but with leading whitespaces (1 or 2 spaces), hence the testcase is failed according to the test_lexer.sh output. Since we cannot change the test_lexer.sh script, would changes have to be made in the makefile or cpp file to remove leading whitespaces (if any) or is this an issue within the test_lexer.sh script?

**Comment by ymherklotz** [comment]
> What does 'Segmentation fault: 11' mean here?

Segmentation faults often occur because of unauthorised accesses to memory
(https://stackoverflow.com/questions/2346806/what-is-a-segmentation-fault).  So
it may be that you are trying to read a value from memory after it has been
deallocated.  You can try and have a look at all your interactions with memory
to see if you are sure that you are reading from a valid address.  Especially if
you are passing data from the lexer to your main function, you need to be sure
that you have allocated it properly.

> Since we cannot change the test_lexer.sh script, would changes have to be made
> in the makefile or cpp file to remove leading whitespaces (if any) or is this
> an issue within the test_lexer.sh script?

I think this may just be because one last part of the spec needs to be
implemented, especially the following point, which you might need to handle in
your lexer:

> All other characters should not be counted (and should not appear in the
> output).

**Comment by ljc20** [comment]
Hello I have the same error as my colleague above and I was looking for possible solutions and therefore wondering if we could modify the flex c++ file and YY_Input of that. Thank you in advance

**Comment by ymherklotz** [comment]
Hi @ljc20, maybe #19 can give some hints? It should not be necessary to modify the flex generated c++ file or YY_INPUT.

**Comment by johnwickerson** [comment]
Hi @ozeidan9, is this issue still causing you problems? If so, please provide further details. If not, please mark this issue as "closed".
