### ISSUE TITLE
Use of the auto type in histogram_main.cpp

### ISSUE THREAD

**Issue by ifte-c** [LangProc/langproc-2021-lab#16]
Why is the auto type used here? Is it just convenient?

![image](https://user-images.githubusercontent.com/91498574/150809272-6ff871a9-49fb-4763-9a46-fd914f1a849b.png)

**Comment by ifte-c** [comment]
That makes a lot more sense now, thank you! I'm not sure how a pointer could be used for ```sort_order``` since the ```sort``` function below takes a function that returns a boolean as its input. Perhaps ```sort_order``` could return a ```std::pair<std::string,unsigned> *``` type which iterates through the array?

**Comment by ymherklotz** [comment]
Well this isn't just an ordinary pointer, sort_order in this case is a pointer to a function instead of to data.  For example, a simpler example, which might help, is the following, where `f` is a function pointer which points to the `add1` function, but can point to any function that takes an `int` and returns an `int`:

```c
int add1(int a) { return a + 1; }

int main() {
    int (* f)(int) = &add1;
    return f(10);
}
```

**Comment by johnwickerson** [comment]
Hi @ifte-c, if this issue is now sorted, please could you mark this issue as closed? Thanks.
