### ISSUE TITLE
LAB2: Associativity for Negative Exponentials

### ISSUE THREAD

**Issue by Nikhil-Narayanan** [LangProc/langproc-2021-lab#73]
Hi I was wondering how we should define the grammar for exponentials - I put them ahead of the unary (so unary is evaluated before exponential) to accomodate the test case x^-1.5

However, this would also imply that -3^2 = 9

Is that ok?

https://en.wikipedia.org/wiki/Order_of_operations
They mention that this is the way things are done in excel so I guess it's better suited to lab 2?

**Comment by ymherklotz** [comment]
Yeah I think that is the right order of operations.

**Comment by Nikhil-Narayanan** [comment]
Ok great, thanks!

**Comment by simon-staal** [comment]
I don't think that's correct, I'd argue that -3^2 = -9 since the unary minus is equivalent to multiplying by a -1. If you try writing -3^2 in a calculator, google or wolfram alpha that's the result it'll give you. In the context of this lab I'm not sure if it's the desired behavior, but it is certainly possible to get your parser to work that way.

**Comment by Nikhil-Narayanan** [comment]
You just have to switch the order of the unary and the exponential grammars I think (that's what I had originally actually and ran into the error with x^-1.5). Which would you say is desired for this lab?

**Comment by simon-staal** [comment]
UPDATE: Correct behavior is -9

**Comment by ymherklotz** [comment]
Yeah, I was wrong, I agree with @sts219. -3^2 = -9. Different calculators do different things though, they are technically both valid but we choose: -3^2 = -(3^2) = -9.

**Comment by Nikhil-Narayanan** [comment]
Do we need to make more specific grammars which incorporate what happens if a minus comes before an exponential and if a minus comes after an exponential?

**Comment by ymherklotz** [comment]
Yeah it does complicate the grammar a bit, it's not just nicely written in the same style. You basically will need to be more specific but also be careful with associativity of `^`.

**Comment by Nikhil-Narayanan** [comment]
Could I call one of you on teams about this by any chance?

**Comment by johnwickerson** [comment]
The issue, in my mind, has to do with whether you think of something like `-5` as a single integer literal, or as the unary-minus operation applied to the integer literal `5`. If you take the former view, then `-5^2` should be parsed as `(-5)^2` because you can't break apart the `-5`. If you take the latter view then `-5^2` tends to be parsed as `-(5^2)` because exponentiation binds more tightly than `-` (if you think of `-5` as `0-5`) or `*` (if you think of `-5` as `(-1)*5`).

**Comment by Nikhil-Narayanan** [comment]
I'm confused about the type of $$ in this case

**Comment by Nikhil-Narayanan** [comment]
> 

So we should definitely consider -5 as 0-5 as opposed to (-1)*5?

**Comment by johnwickerson** [comment]
> > 
> 
> So we should definitely consider -5 as 0-5 as opposed to (-1)*5?

Is there a difference?

**Comment by Nikhil-Narayanan** [comment]
It would make unary fall under the same priority as addition/subtraction as opposed to multiplication/division?

**Comment by johnwickerson** [comment]
> It would make unary fall under the same priority as addition/subtraction as opposed to multiplication/division?

Can you think of an arithmetic expression that can expose that distinction?

**Comment by Nikhil-Narayanan** [comment]
I can't, are they exactly the same?

**Comment by johnwickerson** [comment]
I can’t either ;-)
