### ISSUE TITLE
LAB2: Log testing

### ISSUE THREAD

**Issue by AndyWanna** [LangProc/langproc-2021-lab#81]
Would our parser ever be tested with and input like log2 (a logarithm without the surrounding brackets), which we have to recognise as invalid?

**Comment by BPulmannova** [comment]
`test_parser.sh` already checks for a couple of invalid inputs, ensuring they are not successfully evaluated (e.g. syntax error is good). Remaining 50% of the marks will come from unseen testcases, but I think the specification answers whether your parser could be tested with such input and what is its expected behaviour.
